### PR TITLE
Fixes for SO5

### PR DESCRIPTION
**Pull request by GibsT**
Strips inline comments from being sent to the serial port which will lock up a SO5. SO5 PID was added to the valid PID list.

### CODE REVIEW

**Comment by kglovern** [comment]
This is just the equivalent fix for bracket comments on Shapeoko firmware as https://github.com/Sienci-Labs/gsender/pull/450 with the PID added?  We'll likely merge this in for next build instead of that one.

**Comment by GibsT** [comment]
> This is just the equivalent fix for bracket comments on Shapeoko firmware as #450 with the PID added? We'll likely merge this in for next build instead of that one.

Yes it is.

**Comment by gsrunion** [comment]
Yep. I have been meaning to close my PR. When would these changes be available on a build, edge or otherwise?

**Comment by kglovern** [comment]
This is live as of 1.4.1, thank you both for your contributions.

**Pull request merged**
